# Generated by Django 3.2.4 on 2021-06-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sikud', '0002_auto_20210626_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('provinsi_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sikud.provinsi')),
            ],
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kabupaten_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sikud.kabupaten')),
            ],
        ),
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kecamatan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sikud.kecamatan')),
            ],
        ),
    ]
